apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: db:5432
    database: waternet_db
    user: admin
    secureJsonData:
      password: password123
    jsonData:
      sslmode: 'disable'